---
- name: configure lamp
  hosts: webserver
  become: yes
  become_method: sudo
  vars_files:
    - vars/default.yml
  roles:
    - apache
    - letencrypt
    - postfix

- name: configure database mariadb
  hosts: database
  become: yes
  become_method: sudo
  vars_files:
    - vars/default.yml
  roles:
    - mariadb

